### ISSUE TITLE
How to get a list of files contained in a torrent file

### ISSUE THREAD

**Issue by barnett2010** [vinhtq115/rename-torrent-from-hash#2]
thank you so much 。
I have more than 200,000 seeds,
All hash names
Now I can know what are their names 

------------------------------
How to get a list of files contained in a torrent file
magnet:?xt=urn:btih:45C9991DD77E65BDE9B46E26D5796A0918AEF4C3
hash=45C9991DD77E65BDE9B46E26D5796A0918AEF4C3
name=MARVEL

file list= 
Thor.2011.BDREMUX.2160p.HDR.mkv - 55.86 GB
Iron Man.2008.UHD.BluRay.Remux.2160p.mkv - 63.80 GB
Captain Marvel.2019.BDREMUX.2160p.HDR.mkv - 45.73 GB
Ant-Man.2015.BDREMUX.2160p.HDR.seleZen.mkv - 51.30 GB

how to get file list?

**Comment by vinhtq115** [comment]
Sorry for late response.

The `torrentool.api.Torrent` has a `files` property that can be used to get all the files in the torrent file. More details at [torrentool/torrent.py](https://github.com/idlesign/torrentool/blob/5f37d6dcc304758bae46d01c63e5be0f0a348bfc/torrentool/torrent.py#L83)
